volumes:
  splunk-var:
  splunk-etc:
  splunk-usr:
  splunk-sysloc:

services:
  splunk:
    image: docker.io/splunk/splunk:10.2.1-rhel9
    container_name: splunk
    hostname: splunk
    restart: unless-stopped
    environment:
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_GENERAL_TERMS: ${SPLUNK_GENERAL_TERMS}
      SPLUNK_PASSWORD: ${SPLUNK_PASSWORD}
      SPLUNK_LICENSE_URI: ${SPLUNK_LICENSE_URI:-Free}
    ports:
      - "0.0.0.0:8000:8000"
      - "0.0.0.0:8088:8088"
      - "0.0.0.0:8089:8089"
      - "0.0.0.0:9997:9997"
    volumes:
      - splunk-var:/opt/splunk/var
      - splunk-etc:/opt/splunk/etc
      - splunk-usr:/opt/splunk/etc/users
      - splunk-sysloc:/opt/splunk/etc/system/local
