version: "3.6"

networks:
  splunknet:
    driver: bridge
    attachable: true

volumes:
  so1-var:
  so1-etc:

services:
  so1:
    networks:
      splunknet:
        aliases:
          - so1
    image: <NEXT_VERSION_SPLUNK_IMAGE>
    container_name: so1
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=${password}
      - DEBUG=true
      - SPLUNK_UPGRADE=true
    ports:
      - 8000
      - 8089
    volumes:
      - so1-var:/opt/splunk/var
      - so1-etc:/opt/splunk/etc
