name: Snyk Infrastructure as Code

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '39 19 * * 4'

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Snyk to check compose configuration
        continue-on-error: true
        uses: snyk/actions/iac@v1.0.0
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          file: docker-compose.yml
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif
